accent = "#56949f"
cursor = "#286983"
foreground = "#575279"
background = "#faf4ed"
selection_foreground = "#faf4ed"
selection_background = "#d7827e"

color0 = "#f2e9e1"
color1 = "#b4637a"
color2 = "#286983"
color3 = "#ea9d34"
color4 = "#56949f"
color5 = "#907aa9"
color6 = "#56949f"
color7 = "#575279"
color8 = "#9893a5"
color9 = "#b4637a"
color10 = "#286983"
color11 = "#ea9d34"
color12 = "#56949f"
color13 = "#907aa9"
color14 = "#56949f"
color15 = "#797593"
